version: '3.7'
networks: 
    ponorogo-serve:
        driver: bridge
services:
    nginx:
        image: nginx
        container_name: nginx-ponorogo-serve
        restart: unless-stopped
        ports:
            - 80:80
        volumes:
            - ./app:/app
            - ./site.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - postgres
        networks: 
            - ponorogo-serve
    php:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: php-ponorogo-serve
        restart: unless-stopped
        volumes:
            - ./app:/app
            - ./log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
        networks:
            - ponorogo-serve
    postgres:
        image: postgres:14
        container_name: postgres-ponorogo
        restart: unless-stopped
        volumes:
            - ./postgres:/var/lib/postgres
        ports:
            - 5432:5432
        environment:
            POSTGRES_DB: ponorogo
            POSTGRES_USER: webuser
            POSTGRES_PASSWORD: 12345
        networks: 
            - ponorogo-serve
    pgadmin:
        depends_on:
            - nginx
        image: dpage/pgadmin4
        ports:
            - 5050:80
        environment:
            PGADMIN_DEFAULT_EMAIL: firman@mail.com
            PGADMIN_DEFAULT_PASSWORD: admin
        restart: unless-stopped
        networks: 
            - ponorogo-serve
